# Sample code for word2vec model

### import libraries

In [1]:
import numpy as np
import pandas as pd
import nltk

### set environments

In [2]:
corpus_add = './sample.txt'
stpwrds = nltk.corpus.stopwords.words('english')
vec_dim = 100
n_window = 5
n_samples = 20  # negative sampling 개수
learning_rate = 0.01
def sigmoid(x):
    return 1 / (1 + np.round(np.exp(-x),10))


### Read sample corpus

In [3]:
corpus_file = open(corpus_add)
text = corpus_file.readline()
# tokenize the corpus
tokens = nltk.word_tokenize(text)

# Stopword 제거
tokens = [k for k in tokens if k not in stpwrds]

# 숫자제거
tokens = [k for k in tokens if not k.isdigit()]

# 처음 5개만 보여주기
tokens[:5] 

['anarchism', 'originated', 'term', 'abuse', 'first']

### Build word matrix

In [4]:
# get the number of unique words in the corpus
unique_words_n = len(set(tokens))

# build standard word matrix
# initialize the elements values
word_matrix = pd.DataFrame(data = np.random.normal(0,0.5,size = (unique_words_n,vec_dim)),
                           index = set(tokens), columns=range(vec_dim), dtype=np.float32)

# 처음 5개만 보여주기
word_matrix.head(5)

0         1         2         3         4         5   \
organization  0.178017  0.012360 -0.503194 -0.459824  0.496037  0.119252   
state         0.154270  0.700720 -0.108441  0.416652  0.194425 -0.358219   
early         0.347029  0.255167  0.717321 -0.582404 -0.573712  0.136319   
experiment   -0.781766  0.176941 -0.143949 -0.162064 -0.011218  0.441700   
american      0.032122 -0.425582  0.474305 -0.960936 -0.497471  0.047829   

                    6         7         8         9     ...           90  \
organization  0.329428 -0.767484  0.207051 -0.192051    ...    -0.114578   
state         0.452353  0.890800  0.410773  0.017911    ...    -0.077098   
early         0.159591 -0.940410  0.160085  0.100121    ...    -0.401748   
experiment    0.274888  1.031349  0.371849  0.732819    ...     0.628236   
american     -0.092854 -0.124465 -0.618539 -0.257411    ...     0.026571   

                    91        92        93        94        95        96  \
organization -0.917741  0.410301 -0.434145 -0.740530 -0.130829  0.092579   
state        -0.513307 -1.016771 -0.379128  1.048174 -0.975451  0.377770   
early         0.351940 -0.308923  0.806720 -0.458799 -0.378255  0.116207   
experiment    0.478328  0.078996  0.946773 -0.288128  0.000134  0.911601   
american     -0.313493  0.604312 -0.515188 -0.887631 -0.108320  0.135509   

                    97        98        99  
organization -0.116697  0.320323  0.990064  
state         0.416691  0.429590 -0.162068  
early         0.511778 -0.303354  0.428216  
experiment    0.544589 -0.892710  0.840078  
american     -0.154214  0.007211 -0.198859  

[5 rows x 100 columns]

### Settings for negative sampling

In [5]:
# Negative sampling을 위한 단어별 확률분포 생성
# 해당어 확률 = [해당어 빈도수^(3/4)] / [빈도수^(3/4)의 총합]
total_num_words = len(tokens)       # 중복 허용한 모든 token 갯수
freqdist = nltk.FreqDist(tokens)    # corpus 내 token의 빈도수
word_temp1 = pd.DataFrame([freqdist])
word_temp1 = word_temp1/ total_num_words
word_temp1 = pow(word_temp1, 0.75)
denom = word_temp1.sum(axis = 1)[0] # 모든 word_temp1들의 합을 분모로
word_prob = word_temp1 / denom   # 클래스 변수에 바로 할당
word_idx = word_prob.columns
word_prob = word_prob.values[0].tolist()

## Starts train (just for 1 iteration)

### Get input word

In [6]:
input_word = tokens[n_window]
input_word

'used'

### Positive sample

In [7]:
positive_sample = tokens[:n_window] + tokens[n_window + 1 : n_window + n_window + 1]
positive_sample

['anarchism',
 'originated',
 'term',
 'abuse',
 'first',
 'early',
 'working',
 'class',
 'radicals',
 'including']

### Negative sample

In [8]:
return_idx = np.random.choice(np.arange(unique_words_n), size=n_samples, replace=False, p=word_prob)
negative_sample = word_idx[return_idx].tolist()
negative_sample

['accepted',
 'septentrionale',
 'property',
 'concerning',
 'related',
 'relations',
 'proudhon',
 'including',
 'one',
 'rothbard',
 'moment',
 'anarchism',
 'organisation',
 'interest',
 'inclined',
 'description',
 'published',
 'many',
 'find',
 'power']

### Input word vector

##### which means hidden layer in the network

In [9]:
input_word_vector = word_matrix.ix[input_word]
input_word_vector.head()

0   -1.008624
1   -1.051884
2    0.186226
3    0.016142
4    0.522768
Name: used, dtype: float32

### Sample word vectors 

##### which mean W_2 in the network

In [10]:
sample_word = set(positive_sample + negative_sample)
sample_word_vector = word_matrix.ix[sample_word]
W_2 = sample_word_vector
W_2.head()

0         1         2         3         4         5   \
including   0.740121  0.326963  0.116851 -0.679121  0.909204 -0.300451   
early       0.347029  0.255167  0.717321 -0.582404 -0.573712  0.136319   
interest    0.072003 -0.981782 -0.010239  0.043778 -0.114370 -0.364081   
concerning -0.085401 -0.134851  0.429632  0.607253 -0.458640 -0.254063   
accepted   -0.225716  0.064858  0.265654 -0.464554 -0.250714  1.257679   

                  6         7         8         9     ...           90  \
including   0.379016  0.033540 -0.689721 -0.816815    ...    -0.118457   
early       0.159591 -0.940410  0.160085  0.100121    ...    -0.401748   
interest   -0.480681  0.284645 -0.455918 -0.131446    ...    -0.690226   
concerning  0.089445  0.024281  0.202941  0.828504    ...    -0.402616   
accepted   -0.731250  0.411240  0.218622  0.001807    ...     0.297231   

                  91        92        93        94        95        96  \
including   0.196268 -0.017542  0.406544 -0.043290  1.109424 -0.443299   
early       0.351940 -0.308923  0.806720 -0.458799 -0.378255  0.116207   
interest   -0.146965 -0.408784 -0.165564  0.118621 -0.062836 -0.468301   
concerning  0.330462  1.107138  0.298232  0.477581  0.923810  0.485569   
accepted   -0.773950 -0.386476 -0.322347 -0.878875  0.326871 -0.143735   

                  97        98        99  
including   0.423337 -0.539742  0.026163  
early       0.511778 -0.303354  0.428216  
interest   -0.296385 -0.030050  0.617558  
concerning -0.619266  0.207266  0.637589  
accepted    0.417166 -0.628345  0.097590  

[5 rows x 100 columns]

### Label data expressed 't'

In [11]:
output_size = len(sample_word)
t = pd.DataFrame(data = np.zeros(output_size), index = sample_word)
t.ix[positive_sample] = 1
t = t.values[:,0]
t

array([ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,
        0.,  0.])

### Output layer

In [12]:
hidden_layer = input_word_vector.values
hidden_layer = hidden_layer.reshape([1,vec_dim])
output_layer = sigmoid(np.dot(W_2, hidden_layer.T))  
output_layer = output_layer.reshape([1, output_size])
output_layer

array([[ 0.43614423,  0.35265267,  0.41607535,  0.56135166,  0.26467645,
         0.67611516,  0.5656935 ,  0.83834314,  0.49247238,  0.75924212,
         0.94391167,  0.96142739,  0.90824676,  0.44844458,  0.84265763,
         0.04379153,  0.22700165,  0.05689625,  0.71179259,  0.9695062 ,
         0.58161747,  0.48007843,  0.04298136,  0.01124441,  0.97288418,
         0.49216807,  0.8620277 ,  0.76595682]], dtype=float32)

### Loss 1

In [13]:
loss1 = output_layer - t
loss1 = loss1.reshape([output_size,1])  # dot 계산을 위해서 reshape
loss1

array([[-0.56385577],
       [-0.64734733],
       [ 0.41607535],
       [ 0.56135166],
       [ 0.26467645],
       [ 0.67611516],
       [ 0.5656935 ],
       [-0.16165686],
       [ 0.49247238],
       [-0.24075788],
       [ 0.94391167],
       [ 0.96142739],
       [ 0.90824676],
       [-0.55155542],
       [ 0.84265763],
       [-0.95620847],
       [ 0.22700165],
       [ 0.05689625],
       [ 0.71179259],
       [-0.0304938 ],
       [-0.41838253],
       [ 0.48007843],
       [-0.95701864],
       [ 0.01124441],
       [-0.02711582],
       [ 0.49216807],
       [ 0.8620277 ],
       [ 0.76595682]])

### E

In [14]:
E = np.dot(loss1, hidden_layer)
E

array([[ 0.56871864,  0.59311089, -0.10500486, ..., -0.21230315,
        -0.6072509 , -0.01142167],
       [ 0.65293026,  0.68093434, -0.1205532 , ..., -0.24373942,
        -0.69716809, -0.0131129 ],
       [-0.41966371, -0.43766303,  0.07748424, ...,  0.15666082,
         0.44809709,  0.00842817],
       ..., 
       [-0.49641268, -0.51770374,  0.09165472, ...,  0.18531127,
         0.53004601,  0.00996953],
       [-0.8694621 , -0.9067532 ,  0.16053237, ...,  0.32457094,
         0.92837056,  0.01746154],
       [-0.77256267, -0.80569776,  0.14264142, ...,  0.2883983 ,
         0.82490593,  0.0155155 ]])

### Updated W_2

In [15]:
W_2_updated = W_2 - (learning_rate * E )
W_2_updated

0         1         2         3         4         5   \
including       0.734434  0.321032  0.117901 -0.679030  0.912152 -0.299862   
early           0.340500  0.248357  0.718527 -0.582300 -0.570328  0.136995   
interest        0.076200 -0.977406 -0.011014  0.043711 -0.116545 -0.364516   
concerning     -0.079739 -0.128946  0.428587  0.607162 -0.461575 -0.254649   
accepted       -0.223046  0.067642  0.265161 -0.464596 -0.252098  1.257402   
relations       0.561545 -0.366048 -0.941935  0.148983  0.281081  0.319473   
related         0.712442 -0.743974  0.837177 -0.037657 -0.173902  0.579249   
class           0.170868 -0.479523 -0.159625 -0.910371  0.720062 -0.687383   
organisation    0.020319  0.273812  0.215488  0.709826 -1.085477 -0.345429   
originated      0.200388  0.825900  0.248848 -0.100319  0.551914 -0.331153   
septentrionale -0.601261 -0.478405  0.022878  0.024526  1.247367 -0.360140   
power           0.334214 -1.075223 -1.041256  0.073867  0.432047  0.481564   
property       -0.109885  0.106256 -0.850273 -0.035671 -0.028533  0.387413   
abuse           0.070619 -0.360433  0.102821  1.084534  0.264475 -0.808247   
find            0.615215  0.025479 -0.151250 -0.031862 -0.509449 -0.121099   
first           0.852357  0.510809  0.742218 -0.751846 -0.348498  0.056649   
inclined        0.573682 -0.243591  0.233900  0.028070 -0.226644 -0.169120   
description    -0.035136  0.090352  0.771373 -0.003181  0.120670  0.136552   
proudhon        1.033636  0.047412  0.202836 -0.102405  1.276062 -0.701301   
working         0.349485 -0.925445 -0.066596 -0.043488  0.353987  0.688015   
anarchism       0.232003 -0.122780 -0.102354 -0.122582 -0.184745 -0.209142   
published      -0.073305  0.902210  0.670398 -0.293953  0.423857 -0.932989   
radicals        0.202365  0.938648 -0.189136  0.708609 -0.285042  0.740717   
many            0.633689 -0.065764 -0.523409 -1.049892  0.024384  0.239280   
term           -0.154045 -0.116675  0.037157  0.262215  0.281772 -0.337848   
moment         -0.014020  0.293270 -0.024612 -0.003566  0.006319 -0.127639   
one             0.074070  0.778244 -0.823526  0.587851  1.550274 -0.272674   
rothbard       -0.286131  0.943395 -0.560209  0.832658 -0.174716 -0.440002   

                      6         7         8         9     ...           90  \
including       0.383608  0.033802 -0.692735 -0.816438    ...    -0.119073   
early           0.164863 -0.940110  0.156625  0.100554    ...    -0.402456   
interest       -0.484070  0.284452 -0.453694 -0.131724    ...    -0.689771   
concerning      0.084873  0.024021  0.205942  0.828129    ...    -0.402003   
accepted       -0.733405  0.411117  0.220037  0.001630    ...     0.297520   
relations       0.194546  0.681491  0.081489  0.316217    ...    -0.017412   
related        -0.368772 -0.118076  0.166707  0.905029    ...     0.161729   
class           0.706359  0.432734 -0.463275  0.282448    ...     0.009837   
organisation   -0.153258  0.144962 -0.353311  0.211769    ...    -0.531520   
originated      0.118834 -0.542850  0.550593 -0.085135    ...     0.063964   
septentrionale  0.223156 -0.788269 -0.040414 -0.159251    ...    -0.023728   
power           1.343846  0.309610  0.332755  0.561593    ...    -0.003483   
property       -0.066886 -0.801593  0.266760  0.874255    ...    -0.735786   
abuse          -0.633886 -0.112730 -0.694804  0.719286    ...    -0.658886   
find            0.635514  0.820735 -0.663890  0.382478    ...     0.281235   
first          -0.623658  0.436825  0.492360 -0.331161    ...     0.758368   
inclined       -0.750760 -0.499740  0.152268 -0.343282    ...     0.239842   
description     0.277287  0.155116 -0.016219 -0.874727    ...    -0.293308   
proudhon        0.376818 -0.234901  0.411164  0.148033    ...     0.731130   
working         0.409776  0.257755 -0.682934  1.140344    ...    -0.306364   
anarchism      -0.121049  0.174390  0.267738 -1.687395    ...    -0.218105   
published      -0.396398 -0.263113  0.36426

### EH

In [16]:
EH = np.sum(np.dot(loss1, hidden_layer), axis = 0)
EH

array([ -5.73443403e+00,  -5.98038301e+00,   1.05877215e+00,
         9.17715958e-02,   2.97214634e+00,   5.93716323e-01,
         4.63030176e+00,   2.64220559e-01,  -3.03906967e+00,
         3.80124862e-01,  -1.63573773e+00,   4.02039443e-01,
         3.75374222e+00,   3.82587645e+00,   7.68113094e-01,
         8.11074141e-01,   1.30169056e+00,   6.49754122e-03,
         3.26352407e+00,  -1.27272951e+00,  -1.60448401e+00,
         1.44600884e+00,  -1.06122934e+00,   2.10430067e+00,
        -3.09392392e+00,  -3.24218740e+00,   3.65527171e-01,
         3.78359079e+00,  -6.81368464e+00,  -2.66663878e-01,
         1.51146181e-01,   6.34437524e-01,  -2.28006701e+00,
         1.86471985e+00,  -1.22901853e+00,   4.96351817e-01,
        -3.22436928e+00,   1.35935384e+00,   1.77922508e+00,
        -3.30203838e+00,   5.40425225e-01,   3.07789100e+00,
         1.02265607e+00,  -7.07132596e-01,  -1.25753260e+00,
        -3.54663389e+00,  -2.56373395e+00,   2.55871011e+00,
        -2.43825817e-01,

### Updated input word vector

In [17]:
input_word_vector_updated = input_word_vector - learning_rate * EH.T
input_word_vector_updated

0    -0.951280
1    -0.992080
2     0.175639
3     0.015224
4     0.493047
5     0.098491
6     0.768116
7     0.043831
8    -0.504148
9     0.063059
10   -0.271351
11    0.066694
12    0.622705
13    0.634671
14    0.127422
15    0.134548
16    0.215936
17    0.001078
18    0.541383
19   -0.211132
20   -0.266166
21    0.239877
22   -0.176046
23    0.349080
24   -0.513248
25   -0.537843
26    0.060637
27    0.627656
28   -1.130316
29   -0.044237
        ...   
70   -0.362986
71   -0.993482
72    0.035586
73   -0.653232
74    0.187010
75    0.329066
76    0.202640
77    1.805390
78   -0.262456
79   -0.738214
80    0.333580
81   -0.132500
82    0.291289
83    0.570336
84   -0.200879
85   -0.252269
86   -0.119447
87    0.062601
88   -0.101042
89    0.276966
90   -0.103132
91    0.103311
92   -0.389464
93    0.707730
94    0.297154
95    0.612143
96    0.073668
97    0.355114
98    1.015732
99    0.019105
Name: used, dtype: float64

### Update word matrix

In [18]:
word_matrix.ix[input_word] = input_word_vector_updated
word_matrix.ix[sample_word] = W_2_updated

word_matrix

0         1         2         3         4         5   \
organization  0.178017  0.012360 -0.503194 -0.459824  0.496037  0.119252   
state         0.154270  0.700720 -0.108441  0.416652  0.194425 -0.358219   
early         0.340500  0.248357  0.718527 -0.582300 -0.570328  0.136995   
experiment   -0.781766  0.176941 -0.143949 -0.162064 -0.011218  0.441700   
american      0.032122 -0.425582  0.474305 -0.960936 -0.497471  0.047829   
refers        0.643002  0.240671  0.243144 -0.007076 -0.452451 -0.025668   
works         0.048489 -0.460001 -0.673984 -0.184851  0.559281 -0.834754   
elements     -0.495332  0.118620 -0.102118 -0.194777  0.097554 -0.782855   
zero         -0.899467  0.762909  0.804438 -0.163444  0.405143 -0.069352   
predecessors -0.054446  0.318987 -0.020159 -0.412162 -0.996863  0.259839   
rique         0.723252 -0.144043 -1.193956  0.136045  0.010770 -0.468257   
organized     0.277885 -0.651033 -0.502508  0.660741 -0.250013  0.343092   
experimenal   0.475279  1.283310 -0.022722  0.092466  0.522532 -0.347990   
form          0.501163  0.219562  0.345306  1.628243 -0.001208 -0.240595   
benjamin      0.052925 -1.058987 -0.891055  0.408143  0.464241 -0.935019   
western      -0.357128 -0.061147 -0.157393 -0.922172  0.233647  0.188415   
answers       1.226005  0.708772  0.019262 -0.429712  0.266743 -0.352242   
says         -0.009516  0.263741  0.150202  0.858335 -0.344439  0.267281   
division     -0.730437 -0.411591  0.218032  0.704525  0.251962 -0.082522   
attitudes    -0.238790 -0.315430 -0.328090 -0.407610 -0.185202 -0.475776   
rights       -0.033750  0.374731 -0.254782 -0.043965 -0.546754 -0.240996   
notes         0.322319  0.498555 -0.469107  0.512561 -0.092334  0.344833   
means        -0.478926  0.118351  0.009247  0.272085  0.140593 -0.333947   
term         -0.154045 -0.116675  0.037157  0.262215  0.281772 -0.337848   
brought       0.835559 -0.063752 -0.049653 -0.020654 -0.355409 -0.521449   
long         -1.093574  0.103928 -0.249405 -0.205943  0.030150  0.335218   
claim         0.542294 -0.037005 -0.783284  0.179066  0.114707  0.245301   
girondins     0.528076 -0.014547 -0.363627 -0.577248 -0.490838  0.885642   
lacked        0.055051 -0.366907  0.747407 -0.469056  0.143182 -0.109820   
nevertheless  0.225821 -0.355359 -0.640815 -0.759095  0.470120  0.291647   
...                ...       ...       ...       ...       ...       ...   
every         0.207504 -1.127074  0.375849  0.736067 -0.366687 -0.237597   
good          0.211157 -0.455202 -0.374716  0.044483  0.432179 -0.436052   
anabaptists  -0.317757  0.379657  1.005300 -0.096401  0.094419 -0.523544   
together     -0.121386  0.096075 -0.126246  0.024974 -0.459067 -0.117546   
elimination   0.249048 -0.116913  0.207578 -0.039582  0.537641  0.191476   
greek        -0.312765 -0.258077  0.385714 -0.266183  0.278167  0.036323   
writes       -0.306503  0.634218 -0.559594 -0.165606  0.788327 -0.113302   
pejorative   -0.102613 -0.350427 -0.136698 -0.411158  0.326774 -0.408871   
indigenous    0.699120  0.441777  0.108951 -0.525862  0.258656 -0.588278   
anomie        0.710630  0.898761  0.096578  0.573510 -0.557263  0.341242   
rulers       -0.142141 -0.526810  0.091897  0.281982  0.345811  0.522122   
defend        0.251445  0.554836  0.477134 -0.005263 -0.194920  0.422393   
famous        0.239481  0.268775  0.499524  0.443983  0.384334 -0.090914   
political    -0.698915 -0.459582 -0.772804 -0.064321  0.307734 -0.080347   
nine         -0.525316 -0.313155  0.593347 -0.198482 -0.692215  0.149040   
anarchiste    0.300007  0.059842  0.692669 -0.003662  0.020727  0.107856   
english       0.698728  0.012237 -0.803044 -0.258272  0.060471 -0.295148   
easily       -0.490111  0.172570 -0.553267  0.001941  0.350122  1.112045   
using        -0.420048 -0.303973 -0.650659  0.021028  0.744896 -0.219629   
related       0.712442 -0.743974  0.837177 -0.037657 -0.173902  0.579249   
taoism       -0.379791  0.419541 -0.130420 -0.120042 -0.270988 -0.11